### ISSUE TITLE
RepairStructure outputs multiple residues with the same number

### ISSUE THREAD

**Issue by merkys** [xiaoqiah/EvoEF2#3]
EvoEF2 in RepairStructure mode modifies the residue numbers making some of them identical. For example, processing PDB entry `3SGB`:
```
EvoEF2 --command RepairStructure --pdb 3SGB.pdb
```
In the output at least 5 residues are numbered as 48.

**Comment by tommyhuangthu** [comment]
Hello, the 3SGB.pdb has a string of amino acids indexed as 48, 48A, 48B, 48C, and 48D, although they have different identities. As EvoEF2 only scan columns 23-26 for the position of amino acid in a protein chain, all these amino acids will be considered to have position 48. In summary, this is an issue to be solved in EvoEF2 and EvoEF2-like tools (such as EvoEF and UniDesign).

A simple way to solve this problem is reindexing your pdb. Then, you can use EvoEF2 to repair the structure.

Best,
Xiaoqiang

**Comment by merkys** [comment]
You are right, the residues I mentioned indeed have insertion codes. Thank you for the hint.
